spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowCredentials: "true"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
