spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "https://hopital-militaire.azurewebsites.net"
            allowedHeaders: "*"
            allowCredentials: "true"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT